variables:
  POSTGRES_PASSWORD: postgres

stages:
  - build
  - linting
  - testing

build:
  image: python:3.11
  stage: build 
  script:
    - python3 -m venv env
    - source env/bin/activate
    - export PYTHONPATH=$(pwd)
    - pip install -r requirements.txt
    - echo "Build success"
  artifacts:
    paths:
      - env
    expire_in: 1 day

linting:
  stage: linting
  image: python:3.11
  script:
    - source env/bin/activate
    - echo "Linting code"
    - ruff check .
    - echo "Linting success"


testing:
  stage: testing
  image: python:3.11
  services:
    - name: postgres:15-alpine
      alias: postgres
  variables:
    PGPASSWORD: $POSTGRES_PASSWORD
  script:
    - apt update
    - apt install postgresql-client -y
    - psql -h "postgres" -U "postgres" -w -c "CREATE USER $TEST_DB_USER WITH PASSWORD 'postgres' CREATEDB;"
    - psql -h "postgres" -U "$TEST_DB_USER" -W "postgres" -c "CREATE DATABASE $TEST_DB_NAME;"
    - source env/bin/activate
    - export PYTHONPATH=$(pwd)
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
    - echo "Testing success"
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
