image: alpine:latest

stages:
  - build
  # - test
  - linting
  - commit_test
  - merge_test

build:
  image: python:3.11
  stage: build
  script:
    - apt-get update -q -y
    - apt install python3-pip  -y
    - pip install virtualenv
    - python3 -m venv env
    - source env/bin/activate
    - pip install -r requirements.txt

# pytest:
#   stage: test
#   script:
#     - echo "Running tests"
#     - pytest
#   dependencies:
#     - build

pylint:
  stage: linting
  script:
    - echo "Linting code"
    - pylint src
  dependencies:
    - build