stages:
  - build
  - linting

before_script:
  - apt-get update -q -y
  - apt install python3-pip  -y
  - pip install virtualenv
  - python3 -m venv env
  - source env/bin/activate
  - export PYTHONPATH=$(pwd)
  - pip install -r requirements.txt

build:
  image: python:3.11
  stage: build 
  script:
    - echo "Build success"

pylint:
  stage: linting
  image: python:3.11
  script:
    - echo "Linting code"
    - pylint src