image: alpine:latest

stages:
  - build
  - linting


build:
  stage: build
  image: alpine:latest
  script:
    - apt-get update -q -y
    - apt install python3-pip  -y
    - pip install virtualenv
    - python3 -m venv env
    - source env/bin/activate
    - export PYTHONPATH=$(pwd)
    - pip install -r requirements.txt

pylint:
  stage: linting
  alpine:latest
  script:
    - echo "Linting code"
    - pylint src