"""alter_default_book_description

Revision ID: 9ed0d6534222
Revises: a516756d879e
Create Date: 2023-06-26 00:04:24.974223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed0d6534222'
down_revision = 'a516756d879e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
